  version: '3.5'

  networks:
    rinha:
      driver: bridge

  services:
    db: # Banco de dados
      image: mysql:latest
      hostname: db
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: rinhadb
      ports:
        - "3306:3306"
      deploy:
        resources:
          limits:
            cpus: '0.4'
            memory: '0.9GB'
      networks:
        - rinha
     

    api01:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - db
      ports:
        - "9001:3000"
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: '0.8GB'
      networks:
        - rinha
      restart: on-failure


    api02:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - db
      ports:
        - "9002:3000"
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: '0.8GB'
      networks:
        - rinha
      restart: on-failure

    nginx: 
      image: nginx:latest
      depends_on:
        - api02
        - api01
      deploy:
        resources:
          limits:
            cpus: '0.2'
            memory: '0.5GB'
      ports:
        - "9999:9999"
      networks:
        - rinha
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf



